export const portfolioContent = {
  si: [
    { id: 'intro', variant:'sunrise', title: 'අපගේ නාට්‍ය මංගල්‍යය – සම්පූර්ණ පැමිණිල්ල', body: 'ශ්‍රී ලංකා දූපතේ ජාතික පාසල් නාට්‍ය තරගාවලිය සඳහා අපගේ පාසල ගත් පියවර පිළිබඳව මෙම සම්පූර්ණ පැමිණිල්ල ඉදිරිපත් කරයි. මෙහිදී අපගේ නාට්‍යය “රහස් නැටුම” සම්බන්ධ සියලු සැලසුම්, පුහුණු, ඇඳුම් සහාය, වේදිකා සැලසුම්, පසුබිම් සූදානම්, අරමුදල් එකතු කිරීම සහ අවසාන වේදිකා ප්‍රදර්ශනය පිළිබඳ සවිස්තරාත්මක වාර්තාවක් ඇතුළත් වේ.' },
    { id: 'theme', variant:'violet', title: 'නාට්‍යය සහ තේමා', body: 'අපගේ නාට්‍යය ‘රහස් නැටුම’ යනු අතීතය හා වර්තමානය සම්බන්ධ කරමින්, සමාජයේ සත්‍යය හෙළිදරව් කරන ගැඹුරු නාට්‍යයක් වේ. මෙම කෘතිය තුළින් සමාජය තුළ ඇති අසාධාරණය සහ අධිකාරිය අභියෝගයට ලක් කරන ආකාරය නාට්‍යමය රටාවකින් ඉදිරිපත් කෙරේ.' },
    { id: 'costumes', variant:'amber', title: 'ඇඳුම් සැලසුම් සහ සූදානම්', body: 'ඇඳුම් සැලසුම් කරන ලද්දේ පුරාණ ඊජිප්තුවේ රජයන් සහ ජනතාවගේ රටාව අනුවයි. සිසුන් හා ගුරුවරුන්ගේ සෘජු සහයය යොදා ගනිමින් ඇඳුම් හස්තකෘතියෙන් සකස් කරන ලදී. [ඇඳුම් සූදානම් පිළිබඳ ඡායාරූප යොදන්න]' },
    { id: 'props', variant:'teal', title: 'වේදිකා සහාය / Props', body: 'වේදිකා සැලසුම් සහ පසුබිම් නිර්මාණය සදහා විශේෂ සැලසුම් සකස් කරන ලදී. ඉගුරු, ගෙඩි, ගහන සහ විවිධ ද්‍රව්‍ය භාවිතා කරමින් පුරාණ පසුබිමක් නැඟිටුවන ලදී. [Props සහ පසුබිම් සැලසුම් පිළිබඳ ඡායාරූප යොදන්න]' },
    { id: 'rehearsals', variant:'pink', title: 'පුහුණු සහ සූදානම්', body: 'නිරන්තර පුහුණු සැසි පැවැත්වීම තුළින් සිසුන්ගේ වේදිකා චරිත නිවැරදිව ඉදිරිපත් කළ හැකි විය. ගුරුවරුන්ගේ මගපෙන්වීම යටතේ ප්‍රතිදානය සහ ක්‍රියාදාම වැඩි දියුණු කළා. [පුහුණු සැසි පිළිබඳ ඡායාරූප යොදන්න]' },
    { id: 'fundraising', variant:'lime', title: 'අරමුදල් එකතු කිරීම', body: 'අරමුදල් එකතු කිරීම සඳහා පාසල් සිසුන් හා ගුරුවරුන්ගේ සහභාගීත්වයෙන් කෑම හා පාන විකුණන වැඩසටහන් පැවැත්විය. මේ මගින් ඇඳුම්, වේදිකා සහ අමතර අවශ්‍යතා සඳහා මුදල් එකතු කරන ලදී. [අරමුදල් එකතු කිරීමේ ඡායාරූප යොදන්න]' },
    { id: 'final-day', variant:'ocean', title: 'අවසාන වේදිකා දින', body: 'අවසාන දිනයේදී, අපගේ නාට්‍යය වේදිකා ගත කරන ලද අතර, සියලුම ශිෂ්‍යයන්ගේ ඉමහත් උනන්දුව සහ සහයෝගය මත දිනුව. රංගනයේදී වේදිකාව වර්ණවත් පසුබිම් සහ ඇඳුම් සමග මනෝහර දර්ශනයක් සපයන ලදී. [අවසාන වේදිකා ප්‍රදර්ශනයේ ඡායාරූප යොදන්න]' },
    { id: 'conclusion', variant:'gold', title: 'නිගමනය', body: 'මෙම නාට්‍යය සාර්ථක කිරීම සඳහා සහභාගී වූ සියලුම ගුරුවරුන්, සිසුන් සහ මව්පියන්ට අපගේ ගෞරවය පිරිනමමු. අපගේ එකමුතුවේ ප්‍රතිඵලයක් ලෙස මෙම ජාතික වේදිකාවේ ගෞරවයෙන් නාට්‍යය ඉදිරිපත් කළ හැකි විය.' }
  ],
  en: [
    { id: 'intro', variant:'sunrise', title: 'Drama Competition Portfolio', body: 'This portfolio presents the complete journey of our drama production, from initial concept development to the final stage performance. It includes costumes, props, fundraising efforts, rehearsals, and the final day of the competition, accompanied by photographs and detailed notes.' },
    { id: 'costumes', variant:'amber', title: 'Costumes and Props', body: 'Our team worked tirelessly to design and prepare costumes that reflect the theme of the drama. Traditional accessories, handmade jewelry, and creative props were crafted with care, bringing authenticity and vibrancy to the stage performance. [Insert Costume & Props Images Here]' },
    { id: 'fundraising', variant:'lime', title: 'Fundraising for Expenses', body: 'To manage the costs associated with the production, the students organized fundraising activities. These included setting up food stalls, where students enthusiastically prepared and sold snacks, creating both a fun experience and a successful way to gather funds for costumes, props, and transport. [Insert Fundraising Images Here]' },
    { id: 'rehearsals', variant:'pink', title: 'Rehearsals and Preparations', body: 'The preparation process involved regular rehearsals, stage setup, and prop arrangements. Students collaborated in building stage backdrops, painting decorations, and practicing their roles to ensure a seamless performance. These moments of teamwork highlight the dedication and unity of the group. [Insert Rehearsal & Preparation Images Here]' },
    { id: 'journey', variant:'ocean', title: 'Journey and Stage Day', body: 'On the day of the competition, the cast and crew traveled together, filled with excitement and anticipation. The stage performance reflected weeks of hard work and creativity, with every member contributing to the success of the production. [Insert Journey & Stage Day Images Here]' },
    { id: 'memories', variant:'violet', title: 'Group Memories', body: 'Beyond the competition, this drama production created lasting memories for both students and teachers. It was a celebration of creativity, teamwork, and cultural expression. [Insert Group Photo & Memories Here]' },
    { id: 'conclusion', variant:'gold', title: 'Conclusion', body: 'This drama portfolio showcases not only the outcome of a stage performance but also the dedication, unity, and creativity of the students and teachers.' }
  ]
};
